### ISSUE TITLE
Incorrect placeholder processing when # symbol present in value

### ISSUE THREAD

**Issue by slavap** [sxtfv/flutter_arb_translator#5]
```json
{
  "partyNum": "Party #{num}",
  "newParty": "New Party"
}
```
Leads to the following error:
```
dart run flutter_arb_translator:main --from en --to de --service deepl
08-14-2023 20:24:51 [ARBTranslator] TRC: Started translation from en to [de]
08-14-2023 20:24:51 [ARBTranslator] TRC: Total entries count: 2
08-14-2023 20:24:51 [ARBTranslator] TRC: Unmodified entries count: 0
08-14-2023 20:24:51 [ARBTranslator] TRC: To translate entries count: 2
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _ARBTranslatorSupportsBulkTranslationToSingleTarget._translateItems (package:flutter_arb_translator/service/arb/translator.dart:721:33)
<asynchronous suspension>
#2      ARBTranslator.translate (package:flutter_arb_translator/service/arb/translator.dart:306:31)
<asynchronous suspension>
#3      main (file:///C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_arb_translator-1.0.9/bin/main.dart:141:24)
<asynchronous suspension>
```

**Comment by sxtfv** [comment]
Okay, I will fix
